<style>
    #App-Module-Controller-Game-Scoreboard
    {
        float: left;
        width: 40%;
        padding: 10px 5% 10px 5%
    }
    .Model.Game.Scoreboard.Header
    {
        overflow: hidden;
        border-bottom: 1px solid <?php echo $this->Module->PrimaryColor['darken'][4]; ?>;
    }
    .Model.Game.Scoreboard.Header .Model.Game.Scoreboard.LeftSide,.Model.Game.Scoreboard.Header .Model.Game.Scoreboard.RightSide
    {
        font: italic 24px bold;
    }
    #App-Module-Controller-Game-Scoreboard .Model.Game.Scoreboard.Line
    {
        padding: 10px 10px 0 10px;
        overflow: hidden;
        border-bottom: 1px solid <?php echo $this->Module->PrimaryColor['darken'][4]; ?>;
    }
    #App-Module-Controller-Game-Scoreboard .Model.Game.Scoreboard.LeftSide
    {
        width: 45%;
        float: left;
        text-align: right;
        padding: 0 5% 0 0
    }
    #App-Module-Controller-Game-Scoreboard .Model.Game.Scoreboard.RightSide
    {
        width: 45%;
        float: left;
        padding: 0 0 0 5%
    }
    #App-Module-Controller-Game-Scoreboard-Body .Model.Game.Scoreboard.Line:nth-of-type(odd)
    {
        background-color:<?php echo $this->Module->PrimaryColor['lighten'][2]; ?>;
    }
    #App-Module-Controller-Game-Scoreboard-Body .Model.Game.Scoreboard.Line:last-child
    {
        border-bottom: 6px double <?php echo $this->Module->PrimaryColor['darken'][4]; ?>;
    }
    .Model.Game.Scoreboard.Footer
    {
        padding: 10px 0 10px 0;
        overflow: hidden;
    }
    .BoxMe
    {
        border: 4px solid blue;
        background-color: white;
        border-radius: 4px;
        padding: 1px 4px 1px 4px;
    }
</style>
