<!--Styling applied to all objects with class identified as Model.Menu-->
<style>
    .Model.Menu
    {
        list-style-type: none;
        padding:0px;
        margin:0;
    }
    .Model.Menu.Item
    {
        padding:0px 10px 0px 0px;
        display:inline
    }
    .Model.Menu.Item a
    {
        text-decoration:none;
        color:mediumpurple
    }
    .Model.Menu.Item a:hover
    {
        text-decoration:underline;
        color:blue;
    }
</style>
