<footer>
    <span id="copyright">Copyright 2014 by Grace Clinic Holdings LLC</span>
</footer>
<style>
    footer
    {
        background-color: #cfe0cf;
        height:50px;
        border:solid 2px #178615;
        clear:both;     /* clear any floating constraints to allow footer to display at bottom */
    }
    #copyright
    {
        margin: 5px 30px 5px 30px;
        float:left;
    }
</style>
