<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>Word Shuffle</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="Word Shuffle Game">
        <meta name="author" content="Jason Derouen">
        <meta name="keywords" content="game">

        <?php
        $httpHost  = "http://".$_SERVER['HTTP_HOST'];
        ?>

    </head>
    <!-- Different layouts can be attached to each module, this one is for the WordShuffle module.  -->
    <!-- Module defined here for instantiation by frontend -->
    <body >
        <!-- Controller / Action content renders here -->
        <?php
        echo $this->layout()->content;
        ?>
    </body>
